#!/bin/bash

LOCALFILES="/usr/local/src"
LOCALAPP="roundcube"
REPCONF="/etc/LibM2"


### téléchargement et installation de l'application

cd /var/www/html
wget https://github.com/messagerie-melanie2/Roundcube-Mel/releases/download/1.4.8.2/Roundcube_Mel_1.4.8.2_ORM_0.6.0.12_20200703175852.tar.gz
tar -xvf Roundcube_Mel_1.4.8.2_ORM_0.6.0.12_20200703175852.tar.gz
chown -R www-data. /var/www/html/webmail

### test de la présence des fichiers de config et copie au besoin

if [ ! -d $REPCONF ]
        then
        mkdir $REPCONF
        chown www-data. $REPCONF
        cp /var/www/html/webmail/vendor/messagerie-melanie2/orm-m2/config/default/* $REPCONF
        echo "nom du serveur de base M2 ?"
        read "nombdd"
        sed -i 's/sgbd.test/'$nombdd'/g' $REPCONF/sql.php
        echo "pensez à changer le login/mdp dans $REPCONF/sql.php"

        echo "nom du serveur de ldap ?"
        read "nombdd"
        sed -i 's/ldap.test/'$nombdd'/g' $REPCONF/ldap.php
	sed -i 's/dc=example,dc=com/ou=boites,ou=mce,ou=fr/g' $REPCONF/ldap.php
        echo "pensez à changer le base Dn de recherche dans $REPCONF/sql.php"
fi


cp $LOCALFILES/$LOCALAPP.conf /etc/nginx/sites-available/$LOCALAPP.conf
rm /etc/nginx/sites-enabled/default

ln -s /etc/nginx/sites-available/$LOCALAPP.conf /etc/nginx/sites-enabled/
mkdir /etc/nginx/certs
mv $LOCALFILES/$LOCALAPP-srv.mce.com.* /etc/nginx/certs

service php7.3-fpm restart
service nginx restart

# conf memcache
cp $LOCALFILES/memcached.conf.roundcube /etc/memcached.conf
service memcached restart

su - postgres -c "psql -U postgres -f $LOCALFILES/roundcube-account.sql"
su - postgres -c "psql -d roundcube -U postgres -f $LOCALFILES/roundcube.sql"

service php7.3-fpm restart

mkdir /var/log/roundcube/
chown www-data. /var/log/roundcube/
