#!/bin/bash

LOCALFILES="/usr/local/src"
LOCALAPP="roundcube"
REPCONF="/etc/LibM2"
SOURCE="https://github.com/messagerie-melanie2/Roundcube-Mel/releases/download/1.4.8.4/Roundcube_Mel_1.4.8.4_ORM_0.6.0.13_20200717153552.tar.gz"
WEB="/var/www/html/webmail"

### téléchargement et installation de l'application

cd /var/www/html
wget -O webmail.tgz $SOURCE
tar -xvf webmail.tgz
chown -R www-data. /var/www/html/webmail

### test de la présence des fichiers de config et copie au besoin

if [ ! -d $REPCONF ]
        then
        mkdir $REPCONF
        chown www-data. $REPCONF
        cp $WEB/vendor/messagerie-melanie2/orm-m2/config/default/* $REPCONF
        echo "nom du serveur de base M2 ?"
        read "nombdd"
        sed -i 's/sgbd.test/'$nombdd'/g' $REPCONF/sql.php
        echo "pensez à changer le login/mdp dans $REPCONF/sql.php"

        echo "nom du serveur de ldap ?"
        read "nombdd"
        sed -i 's/ldap.test/'$nombdd'/g' $REPCONF/ldap.php
	sed -i 's/dc=example,dc=com/ou=boites,ou=mce,ou=fr/g' $REPCONF/ldap.php
        echo "pensez à changer le base Dn de recherche dans $REPCONF/sql.php"
fi



if [ ! -f $WEB/config/config.inc.php ]
	then
	cp $LOCALFILES/config.inc.php $WEB/config/config.inc.php
	echo "nom du serveur imap ?"
        read "nombdd"
	sed -i 's/serverimap/'$nombdd'/g' $WEB/config/config.inc.php
fi


if [ ! -f $REPCONF/config.inc.php ]
        then
        cp $LOCALFILES/config.inc.php.agreg $REPCONF/config.inc.php
	cd $WEB/plugins/mel
 	cp $LOCALFILES/config.inc.php.ori config.inc.php
	cat $LOCALFILES/copylist | while read line
		do
		cp config.inc.php $line
		done

echo "copie des fichiers de configuration par defaut faite" 

fi

echo "correction template mel_larry"
cp $LOCALFILES/resources_elements.html  $WEB/plugins/mel/skins/mel_larry/templates/resources_elements.html




echo "configuration nginx" 
cp $LOCALFILES/$LOCALAPP.conf /etc/nginx/sites-available/$LOCALAPP.conf
rm /etc/nginx/sites-enabled/default

ln -s /etc/nginx/sites-available/$LOCALAPP.conf /etc/nginx/sites-enabled/
mkdir /etc/nginx/certs
mv $LOCALFILES/$LOCALAPP-srv.mce.com.* /etc/nginx/certs

service php7.3-fpm restart
service nginx restart

# conf memcache
cp $LOCALFILES/memcached.conf.roundcube /etc/memcached.conf
service memcached restart

su - postgres -c "psql -U postgres -f $LOCALFILES/roundcube-account.sql"
su - postgres -c "psql -d roundcube -U postgres -f $LOCALFILES/roundcube.sql"

service php7.3-fpm restart

mkdir /var/log/roundcube/
chown www-data. /var/log/roundcube/
