#!/bin/bash

set -x 
set -e 

if [ -f /usr/share/debconf/confmodule ]; then
  . /usr/share/debconf/confmodule
fi


NGINXCONF="/etc/nginx/sites-available/proxy-mail.conf"
NGINXPROD="/etc/nginx/sites-enabled/proxy-mail.conf"


is_initial_configuration() {
# Check if this is the initial configuration and not an upgrade of an
# existing configuration
# Usage: if is_initial_configuration "$@"; then ... fi from top level

        # Plain installation
        if [ "$1" = configure ] && [ -z "$2" ]; then
                return 0
        fi
        # Configuration via dpkg-reconfigure
        if [ "$1" = reconfigure ] || [ "$DEBCONF_RECONFIGURE" ]; then
                return 0
        fi
        return 1
}



#Install
#if is_initial_configuration "$@"; then

    if [ "$DEBIAN_FRONTEND" != "noninteractive" ] ; then
        # Fetching configuration from debconf

	db_get proxy-mail/imapchoice
        CONFTYPE=$RET

	db_get proxy-mail/servername
	NAMESERVER=$RET

	IMAPNAME=""
	SMTPNAME=""
	cat  usr/share/proxy-mail/scripts/header.conf >  $NGINXCONF
	sed -i 's/%%NAMESERVER%%/'$NAMESERVER'/g' $NGINXCONF


		#configuration imap
	if [[ "$CONFTYPE" == *"imap"* ]] ; then
            db_get proxy-mail/imapname
            IMAPNAME=$RET

	# copie du template imap
	cat usr/share/proxy-mail/scripts/imap.conf >>  $NGINXCONF
	sed -i 's/%%IMAPSERVER%%/'$IMAPNAME'/g' $NGINXCONF 
        fi

		#configuration smtp
	if [[ "$CONFTYPE" == *"smtp"* ]] ; then
            db_get proxy-mail/smtpname
            IMAPNAME=$RET

        # copie du template imap
        cat usr/share/proxy-mail/scripts/imap.conf >>  $NGINXCONF
        sed -i 's/%%IMAPSERVER%%/'$IMAPNAME'/g' $NGINXCONF
        fi


	cat  usr/share/proxy-mail/scripts/footer.conf >>  $NGINXCONF
    fi
#fi

ln -s $NGINXCONF $NGINXPROD

exit 0
