#!/bin/bash

#set -x 
set -e 

#   Variables 
#   %%NAMESERVER%%   
#   %%IMAPSERVER%%
#   %%LDAPSERVER%%
#   %%LDAPSERVERTECH%%
#   %%LDAPSERVERBASEDN%%
# 	%%LDAPPASS%%
#   %%SEARCH_DN%%


if [ -f /usr/share/debconf/confmodule ]; then
  . /usr/share/debconf/confmodule
fi


NGINXCONF="/etc/nginx/sites-available"
NGINXPROD="/etc/nginx/mail.conf"
NGINXNAME="proxy-mail.conf"
SCRIPTS="/usr/share/proxy-mail/scripts"

is_initial_configuration() {
# Check if this is the initial configuration and not an upgrade of an
# existing configuration
# Usage: if is_initial_configuration "$@"; then ... fi from top level

        # Plain installation
        if SCRIPTS[ "$1" = configure ] && [ -z "$2" ]; then
                return 0
        fi
        # Configura
tion via dpkg-reconfigure
        if [ "$1" = reconfigure ] || [ "$DEBCONF_RECONFIGURE" ]; then
                return 0
        fi
        return 1
}

mkdir  /etc/nginx/certs
mkdir $NGINXPROD
echo "include "$NGINXPROD"/*.conf;" >> /etc/nginx/nginx.conf


#Install
#if is_initial_configuration "$@"; then

    if [ "$DEBIAN_FRONTEND" != "noninteractive" ] ; then
        # Fetching configuration from debconf

	db_get proxy-mail/imapchoice
        CONFTYPE=$RET

	db_get proxy-mail/servername
	NAMESERVER=$RET

	IMAPNAME=""
	SMTPNAME=""
	cat  usr/share/proxy-mail/scripts/header.conf >  $NGINXCONF/$NGINXNAME
	sed -i 's/%%NAMESERVER%%/'$NAMESERVER'/g' $NGINXCONF/$NGINXNAME


		#configuration imap
	if [[ "$CONFTYPE" == *"imap"* ]] ; then
            db_get proxy-mail/imapname
            IMAPNAME=$RET

	# copie du template imap
	cat usr/share/proxy-mail/scripts/imap.conf >>  $NGINXCONF/$NGINXNAME
	sed -i 's/%%IMAPSERVER%%/'$IMAPNAME'/g' $NGINXCONF/$NGINXNAME
        fi

		#configuration smtp
	if [[ "$CONFTYPE" == *"smtp"* ]] ; then
            db_get proxy-mail/smtpname
            IMAPNAME=$RET

        # copie du template smtp
        cat usr/share/proxy-mail/scripts/smtp.conf >>  $NGINXCONF/$NGINXNAME
        sed -i 's/%%IMAPSERVER%%/'$IMAPNAME'/g' $NGINXCONF/$NGINXNAME
	
	# desactivation de postfix si présent.
	sudo systemctl disable postfix ||  true
	sudo service postfix stop ||  true
        fi


	cat  usr/share/proxy-mail/scripts/footer.conf >>  $NGINXCONF/$NGINXNAME
    fi
#fi

cp /usr/share/proxy-mail/www/* /var/www/html
chown -R www-data. /var/www/html

ln -s $NGINXCONF/$NGINXNAME $NGINXPROD/$NGINXNAME
#rm /default
cp $SCRIPTS/demo.*  /etc/nginx/certs/
cp $SCRIPTS/default /etc/nginx/sites-available/


sudo service nginx restart
sudo service php7.3-fpm restart

echo "la configuration par défaut du LDAP a été appliqué sans le mot de passe technique, il est possile de la modifier dans /var/www/html/ministere_config.ini "

#exit 0

