---
- hosts: localhost
  gather_facts: no
  vars_prompt:
  - name: target_host
    prompt: please enter the target host IP
    private: no
  tasks:
    - add_host:
        name: "{{ target_host }}"
        groups: dynamically_created_hosts

- hosts: dynamically_created_hosts
  user: cyril


  tasks:
  - name: install php7 apache
    apt: name={{item}} state=latest
    with_items:
         - apache2 
         - php
         - php-fpm
         - php-memcached
         - php-mbstring
         - memcached
    become: true


  - name: copy test.php
    copy: src=../test.php dest=/var/www/html/ seuser=www-data
    become: true

  - name: configuration apache
    command: a2dismod mpm_prefork ; a2enmod mpm_event ; a2enmod proxy_fcgi
    become: true

  - name: copy defaut.conf
    copy: src=../000-default.conf dest=/etc/apache2/sites-available/ seuser=www-data
    become: true

  - name: restart apache2
    service:
       name: apache2
       state: restarted
    become: true


  - name: configure memcached
    copy: src=../memcached.conf dest=/etc/memcached.conf seuser=www-data
    become: true

  - name: restart memcached
    service:
       name: memcached
       state: restarted
    become: true

