#!/bin/bash

LOCALFILES="/usr/local/src"

#conf  php avec Nginx
cp $LOCALFILES/test.php /var/www/html/
cp $LOCALFILES/nginx_default_php7 /etc/nginx/sites-enabled/default
service nginx restart

# conf memcache
cp $LOCALFILES/memcached.conf /etc/memcached.conf
service memcached restart

